# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2.xci
# IP: The module: 'interupts_rst_ps7_0_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2.xci
# IP: The module: 'interupts_rst_ps7_0_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_rst_ps7_0_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
