# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/interupts/interupts.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts || ORIG_REF_NAME==interupts} -quiet] -quiet

# IP: bd/interupts/ip/interupts_processing_system7_0_1/interupts_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_processing_system7_0_1 || ORIG_REF_NAME==interupts_processing_system7_0_1} -quiet] -quiet

# IP: bd/interupts/ip/interupts_axi_gpio_0_1/interupts_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_axi_gpio_0_1 || ORIG_REF_NAME==interupts_axi_gpio_0_1} -quiet] -quiet

# IP: bd/interupts/ip/interupts_axi_gpio_1_1/interupts_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_axi_gpio_1_1 || ORIG_REF_NAME==interupts_axi_gpio_1_1} -quiet] -quiet

# IP: bd/interupts/ip/interupts_ps7_0_axi_periph_2/interupts_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_ps7_0_axi_periph_2 || ORIG_REF_NAME==interupts_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/interupts/ip/interupts_rst_ps7_0_100M_2/interupts_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_rst_ps7_0_100M_2 || ORIG_REF_NAME==interupts_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/interupts/ip/interupts_xbar_2/interupts_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_xbar_2 || ORIG_REF_NAME==interupts_xbar_2} -quiet] -quiet

# IP: bd/interupts/ip/interupts_axi_timer_0_0/interupts_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_axi_timer_0_0 || ORIG_REF_NAME==interupts_axi_timer_0_0} -quiet] -quiet

# IP: bd/interupts/ip/interupts_xlconcat_0_0/interupts_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_xlconcat_0_0 || ORIG_REF_NAME==interupts_xlconcat_0_0} -quiet] -quiet

# IP: bd/interupts/ip/interupts_auto_pc_0/interupts_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interupts_auto_pc_0 || ORIG_REF_NAME==interupts_auto_pc_0} -quiet] -quiet

# XDC: bd/interupts/interupts_ooc.xdc
