# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_xbar_2/interupts_xbar_2.xci
# IP: The module: 'interupts_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_xbar_2/interupts_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_xbar_2/interupts_xbar_2.xci
# IP: The module: 'interupts_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/warmup/vivado/Z_lab2/Z_lab2.srcs/sources_1/bd/interupts/ip/interupts_xbar_2/interupts_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interupts_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
